image: Visual Studio 2019

cache:
  - packages

install:
 - choco install sbt -ia "INSTALLDIR=""C:\sbt"""
 - SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
 - java -version
 - sbt version

build_script:
 - sbt update
 - sbt all
