image: Visual Studio 2019
environment:
  JAVA_OPTS: -Xmx3072m -server
  
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Users\appveyor\.sbt -> appveyor.yml

install:
 - git submodule update --init
 - choco install sbt -ia "INSTALLDIR=""C:\sbt""" --version 1.2.8
 - SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
 - java -version

build_script:
 - sbt update
 - sbt all

artifacts:
 - path: '**\NetLogo*.exe'
 - path: '**\NetLogo*.dll'
