image: Visual Studio 2019
environment:
  JAVA_OPTS: -Xmx3072m -server

#cache:
#  - C:\ProgramData\chocolatey\bin
#  - C:\ProgramData\chocolatey\lib
#  - C:\Users\appveyor\.sbt

skip_commits:
  files:
    - '.gitignore'
    - 'Jenkinsfile'

install:
 - git submodule update --init
 - choco install sbt -ia "INSTALLDIR=""C:\sbt""" --version 1.3.10
 - SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
 - java -version

build_script:
 - sbt update
 - sbt all
 - sbt netlogo/compile
 
after_build:
 - 7z a netlogo.zip %APPVEYOR_BUILD_FOLDER%

artifacts:
 - path: netlogo.zip
