on: [push, pull_request]

jobs:
  NetLogo:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive 
     - run: ./sbt update
     - run: ./sbt all
