on: [push, pull_request]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: actions/setup-java@v1
       with:
         java-version: '1.8.0.252'
         java-package: jdk+fx
     - run: ./sbt update
     - name: Build NetLogo
       run: ./sbt all
     - name: Test NetLogo
       run: |
         ./sbt depend
         ./sbt headless/depend
         ./sbt parserJS/test
         ./sbt parserJVM/test
         ./sbt netlogo/test:fast
         ./sbt nogen netlogo/test:fast
         ./sbt threed netlogo/test:fast
         ./sbt headless/test:fast
         ./sbt netlogo/test:medium
         ./sbt nogen netlogo/test:medium
         ./sbt threed netlogo/test:medium
         ./sbt headless/test:medium
         ./sbt nogen headless/test:medium
         ./sbt netlogo/test:slow
         ./sbt threed netlogo/test:slow
         ./sbt netlogo/test:extensionTests
         ./sbt headless/test:slow
