on: [push, pull_request]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: actions/setup-java@v1
       with:
         java-version: '1.8'
         java-package: jdk+fx
     - name: Update Java alternatives
       run: |
         sudo update-alternatives --install /usr/bin/java java /media/mydisk/jdk/bin/java 1
         sudo update-alternatives --config java
     - run: ./sbt update
     - name: Build NetLogo
       run: ./sbt all
     - name: Depend, headless and parsers tests
       run: |
         ./sbt depend
         ./sbt headless/depend
         ./sbt parserJS/test
         ./sbt parserJVM/test
     - name: NetLogo fast tests (error allowed)
       continue-on-error: True
       run: ./sbt netlogo/test:fast
     - name: Other fast tests
       run: |
         ./sbt nogen netlogo/test:fast
         ./sbt threed netlogo/test:fast
         ./sbt headless/test:fast
     - name: Medium tests
       run: |
         ./sbt netlogo/test:medium
         ./sbt nogen netlogo/test:medium
         ./sbt threed netlogo/test:medium
         ./sbt headless/test:medium
         ./sbt nogen headless/test:medium
     - name: Slow tests
       run: |
         ./sbt netlogo/test:slow
         ./sbt threed netlogo/test:slow
         ./sbt netlogo/test:extensionTests
         ./sbt headless/test:slow
