on: [push, pull_request]

jobs:
  NetLogo:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: recursive
     - uses: actions/setup-java@v1
       with:
         java-version: '1.8'
         java-package: jdk-fx
     - run: ./sbt update
     - run: ./sbt all
